comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

ignore:
  - "tests"
  - "inst"
  - "man"
  - "docs"
