#!/bin/bash

# Create minimal documentation files for R package installation
# This script generates skeleton .Rd files based on the NAMESPACE file
# These are temporary placeholders until roxygen2 generates proper documentation

set -e

NAMESPACE_FILE="NAMESPACE"
MAN_DIR="man"

if [ ! -f "$NAMESPACE_FILE" ]; then
  echo "Error: NAMESPACE file not found"
  exit 1
fi

mkdir -p "$MAN_DIR"

echo "Generating minimal .Rd files from NAMESPACE..."

# Read each export from NAMESPACE and create a minimal .Rd file
while IFS= read -r line; do
  if [[ $line =~ ^export\((.*)\)$ ]]; then
    func_name="${BASH_REMATCH[1]}"
    rd_file="$MAN_DIR/${func_name}.Rd"

    echo "Creating $rd_file"

    cat > "$rd_file" <<EOF
% Generated by create-minimal-docs.sh: do not edit by hand
% Please use roxygen2::roxygenise() to generate proper documentation
\name{${func_name}}
\alias{${func_name}}
\title{${func_name}}
\description{
This is a placeholder documentation file. Please run roxygen2::roxygenise()
to generate the full documentation from the roxygen comments in the source code.
}
\usage{
${func_name}(...)
}
\arguments{
\item{...}{Arguments to ${func_name}. See source code for details.}
}
\details{
Please refer to the package source code or run roxygen2::roxygenise() to
generate complete documentation from the roxygen comments.
}
EOF
  fi
done < "$NAMESPACE_FILE"

# Create package documentation
cat > "$MAN_DIR/hgnc.mcp-package.Rd" <<'EOF'
% Generated by create-minimal-docs.sh: do not edit by hand
\name{hgnc.mcp-package}
\alias{hgnc.mcp-package}
\alias{hgnc.mcp}
\docType{package}
\title{
MCP Server for HGNC Gene Nomenclature Resources
}
\description{
Provides tools for accessing HGNC (HUGO Gene Nomenclature Committee) gene
nomenclature resources. Includes functions for searching, resolving, and
validating gene symbols using local cached data and the HGNC REST API.
}
\details{
For full documentation, please run roxygen2::roxygenise() to generate
documentation from the roxygen comments in the source code.
}
\author{
Bulent Arman Aksoy <arman@aksoy.org>
}
\keyword{package}
EOF

echo "Generated $(find $MAN_DIR -name '*.Rd' | wc -l) documentation files"
echo "These are minimal placeholders. Run roxygen2::roxygenise() for full documentation."
