#!/usr/bin/env python3
"""
Generate minimal R documentation (.Rd) files from R source code.
This script extracts function signatures from R files and creates
basic .Rd files that match the actual function parameters.
"""

import os
import re
from pathlib import Path


def extract_function_signature(r_file_path, func_name):
    """Extract function signature from R file, handling multi-line signatures."""
    with open(r_file_path, 'r') as f:
        content = f.read()

    # Find the function definition start
    pattern = rf'(?:^|\n)({re.escape(func_name)}\s*(?:<-|=)\s*function\s*\()'
    match = re.search(pattern, content, re.MULTILINE)

    if not match:
        return None

    # Start after the opening parenthesis
    start_pos = match.end()

    # Balance parentheses to find the matching closing parenthesis
    paren_count = 1
    i = start_pos

    while i < len(content) and paren_count > 0:
        if content[i] == '(':
            paren_count += 1
        elif content[i] == ')':
            paren_count -= 1
        i += 1

    if paren_count == 0:
        # Extract the parameters
        params = content[start_pos:i-1]
        # Clean up whitespace and newlines
        params = re.sub(r'\s+', ' ', params).strip()
        # Remove leading/trailing commas and whitespace
        params = params.strip(', ')
        return params

    return None


def extract_roxygen_title(r_file_path, func_name):
    """Extract title from roxygen comments."""
    with open(r_file_path, 'r') as f:
        content = f.read()

    # Find roxygen comments before the function
    pattern = rf"#'\s+(.+?)\n#'\n.*?{re.escape(func_name)}\s*<-\s*function"
    match = re.search(pattern, content, re.DOTALL)

    if match:
        return match.group(1).strip()

    return func_name.replace('_', ' ').title()


def find_function_in_r_files(func_name, r_dir='R'):
    """Find which R file contains a function."""
    r_path = Path(r_dir)
    for r_file in r_path.glob('*.R'):
        with open(r_file, 'r') as f:
            content = f.read()

        # Match function name at start of line or after newline to avoid partial matches
        pattern = rf'(?:^|\n){re.escape(func_name)}\s*<-\s*function'
        if re.search(pattern, content, re.MULTILINE):
            return r_file

    return None


def parse_params(params_str):
    """Parse function parameters into a list."""
    if not params_str:
        return []

    params = []
    current_param = ''
    paren_depth = 0

    for char in params_str + ',':
        if char == ',' and paren_depth == 0:
            if current_param.strip():
                # Extract just the parameter name (before = or default value)
                param_name = current_param.split('=')[0].strip()
                params.append(param_name)
            current_param = ''
        else:
            if char == '(':
                paren_depth += 1
            elif char == ')':
                paren_depth -= 1
            current_param += char

    return params


def generate_rd_file(func_name, params_str, title, output_dir='man'):
    """Generate an .Rd file for a function."""
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    params = parse_params(params_str) if params_str else []

    rd_content = f"""% Generated by generate-rd-files.py
\\name{{{func_name}}}
\\alias{{{func_name}}}
\\title{{{title}}}
\\description{{
{title}
}}
\\usage{{
{func_name}({params_str if params_str else ""})
}}
"""

    if params:
        rd_content += "\\arguments{\n"
        for param in params:
            rd_content += f"\\item{{{param}}}{{(parameter description)}}\n"
        rd_content += "}\n"

    rd_content += """\\details{
This is an automatically generated documentation file.
For complete documentation, run: roxygen2::roxygenise()
}
"""

    output_path = Path(output_dir) / f"{func_name}.Rd"
    with open(output_path, 'w') as f:
        f.write(rd_content)

    print(f"Generated {output_path}")


def generate_package_rd(output_dir='man'):
    """Generate package-level documentation."""
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    rd_content = """% Generated by generate-rd-files.py
\\name{hgnc.mcp-package}
\\alias{hgnc.mcp-package}
\\alias{hgnc.mcp}
\\docType{package}
\\title{
MCP Server for HGNC Gene Nomenclature Resources
}
\\description{
Provides tools for accessing HGNC (HUGO Gene Nomenclature Committee) gene
nomenclature resources. Includes functions for searching, resolving, and
validating gene symbols using local cached data and the HGNC REST API.
Also provides a Model Context Protocol (MCP) server that exposes these
tools to AI assistants and other MCP-compatible clients.
}
\\author{
Bulent Arman Aksoy <arman@aksoy.org>
}
\\keyword{package}
"""

    output_path = Path(output_dir) / "hgnc.mcp-package.Rd"
    with open(output_path, 'w') as f:
        f.write(rd_content)

    print(f"Generated {output_path}")


def main():
    # Read NAMESPACE file to get exported functions
    namespace_path = Path('NAMESPACE')
    if not namespace_path.exists():
        print("Error: NAMESPACE file not found")
        return 1

    with open(namespace_path, 'r') as f:
        namespace_content = f.read()

    # Extract exported functions
    exports = re.findall(r'export\(([^)]+)\)', namespace_content)

    print(f"Found {len(exports)} exported functions")
    print("Generating .Rd files...\n")

    # Generate package documentation
    generate_package_rd()

    # Generate documentation for each exported function
    for func_name in exports:
        # Find the R file containing this function
        r_file = find_function_in_r_files(func_name)

        if r_file:
            # Extract function signature
            params = extract_function_signature(r_file, func_name)

            # Extract title from roxygen comments
            title = extract_roxygen_title(r_file, func_name)

            # Generate .Rd file
            generate_rd_file(func_name, params, title)
        else:
            print(f"Warning: Could not find function {func_name} in R files")
            # Generate with empty params as fallback
            generate_rd_file(func_name, "", func_name)

    print(f"\nGenerated documentation for {len(exports)} functions")
    print("For complete documentation, run: roxygen2::roxygenise()")
    return 0


if __name__ == '__main__':
    exit(main())
